package es.usc.citius.servando.android.alerts;

public enum AlertType
{
	PROTOCOL_NON_COMPILANCE,
	THERAPY_NON_COMPILANCE,
	SALT_INTAKE,
	SMOKE_INTAKE,
	ALCOHOL_INTAKE,
	BLOOD_PRESSURE_VALUE,
	WEIGHT_VALUE,
	LIQUID_INTAKE,
	SYMPTOM,

	SYSTEM_EVENT
}
